// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace MysteryCrateEditor.Libraries.MysteryCrate.Rewards.MinecraftJson
{

    public class Display
    {

        [JsonProperty("Name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("Lore",NullValueHandling = NullValueHandling.Ignore)]
        public string[] Lore { get; set; }
    }

    public class MojangEnchantData
    {
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public int Id { get; set; }

        [JsonProperty("lvl", NullValueHandling = NullValueHandling.Ignore)]
        public int Lvl { get; set; }
    }
    [JsonObject(MemberSerialization = MemberSerialization.OptIn)]
    public class MojangItem
    {

        [JsonProperty("display", NullValueHandling = NullValueHandling.Ignore)]
        public Display Display { get; set; }

        [JsonProperty("ench", NullValueHandling = NullValueHandling.Ignore)]
        public MojangEnchantData[] Enchants { get; set; }
    }

}
